version: "3.8"
   
services:
    django:
        build: .
        command: /bin/sh ./start_command.sh
        container_name: django
        volumes:
            - ./team-A:/team-A
        environment: 
            - DATABASE_HOST=pgdb
        depends_on:
            - pgdb
        env_file: 
            - ./team-A/.env
    pgdb:
        image: postgres
        container_name: pgdb
        environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    nginx:
        build: ./nginx
        ports: 
            - "80:80"
        depends_on: 
            - django
        volumes:
            - ./team-A:/team-A

